version: "3.8"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: carbonable
      POSTGRES_USER: carbonable
      POSTGRES_DB: carbonable_leaderboard
    ports:
      - 5432:5432

  etcd:
    image: quay.io/coreos/etcd:v3.5.11
    restart: always
    ports:
      - 4001:4001
      - 2379:2379
    environment:
      ETCD_NAME: etcd0
      ETCD_ADVERTISE_CLIENT_URLS: "http://etcd:2379"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
