# First create a pg db
# fly pg create -n carbonable-sepolia-leaderboard-db -o carbonable-labs-444 -r cdg

app = 'carbonable-sepolia-leaderboard-backend'
primary_region = 'cdg'

[build]
build-target = "production"

[env]
NETWORK = "sepolia"

[processes]
synchronizer = "./synchronizer"
indexer = "./indexer"
api = "./api"
aggregator = "./aggregator"


[deploy]
release_command = "./migrate"

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ['api']

[[vm]]
cpu_kind = 'shared'
cpus = 1
memory_mb = 1024
